providers:
  openai:
    - method: post
      url: /chat/completions
    - method: post
      url: /completions
    - method: post
      url: /responses
  anthropic:
    - method: post
      url: /v1/messages