# OpenAI Models
gpt-4:
  - "anthropic/claude-3-7-sonnet"
  - "gemini/gemini-2.5-pro"
  - "ollama/deepseek-r1"
  - "mistral/mistral-large"
  - "bedrock/us.deepseek.r1-v1:0"
gpt-4-turbo:
  - "anthropic/claude-3-7-sonnet"
  - "gemini/gemini-2.5-pro"
  - "ollama/llama4"
  - "mistral/mistral-large"
  - "bedrock/amazon.nova-sonic-v1:0"
gpt-4o:
  - "anthropic/claude-3-7-sonnet"
  - "gemini/gemini-2.5-pro"
  - "ollama/llama4"
  - "mistral/mistral-large"
  - "bedrock/us.deepseek.r1-v1:0"
gpt-4o-mini:
  - "anthropic/claude-3-5-haiku"
  - "gemini/gemini-2.0-flash"
  - "ollama/llama3.2"
  - "ollama/llama3"
  - "mistral/mistral-small"
  - "bedrock/us.anthropic.claude-3-5-haiku-20241022-v1:0"
gpt-4.1:
  - "anthropic/claude-3-7-sonnet"
  - "gemini/gemini-2.5-pro"
  - "ollama/llama4"
  - "mistral/mistral-large"
  - "bedrock/us.deepseek.r1-v1:0"
gpt-4.1-mini:
  - "anthropic/claude-3-5-haiku"
  - "gemini/gemini-2.0-flash"
  - "ollama/llama3.3"
  - "mistral/mistral-small"
  - "bedrock/us.anthropic.claude-3-5-haiku-20241022-v1:0"
gpt-4.1-nano:
  - "anthropic/claude-3-5-haiku"
  - "gemini/gemini-1.5-flash-8b"
  - "ollama/phi4"
  - "mistral/ministral-3b"
  - "bedrock/amazon.nova-micro-v1:0"
gpt-4.5:
  - "anthropic/claude-opus-4-0"
  - "gemini/gemini-2.5-pro"
  - "ollama/deepseek-r1"
  - "mistral/mistral-saba"
  - "bedrock/us.deepseek.r1-v1:0"
o1:
  - "anthropic/claude-sonnet-4-0"
  - "gemini/gemini-2.5-pro"
  - "ollama/deepseek-r1"
  - "mistral/mistral-saba"
  - "bedrock/us.deepseek.r1-v1:0"
o1-mini:
  - "anthropic/claude-3-5-haiku"
  - "gemini/gemini-2.0-flash"
  - "ollama/llama3.3"
  - "mistral/mistral-small"
  - "bedrock/us.anthropic.claude-3-5-haiku-20241022-v1:0"
o1-pro:
  - "anthropic/claude-opus-4-0"
  - "gemini/gemini-2.5-pro"
  - "bedrock/us.deepseek.r1-v1:0"
  - "mistral/mistral-saba"
  - "bedrock/us.anthropic.claude-opus-4-20250514-v1:0"
o3:
  - "anthropic/claude-opus-4-0"
  - "gemini/gemini-2.5-pro"
  - "ollama/deepseek-r1"
  - "mistral/mistral-saba"
  - "bedrock/us.anthropic.claude-opus-4-20250514-v1:0"
o3-mini:
  - "anthropic/claude-3-5-haiku"
  - "bedrock/us.anthropic.claude-3-5-haiku-20241022-v1:0"
  - "gemini/gemini-2.0-flash"
  - "ollama/llama3.3"
  - "mistral/mistral-small"
  - "bedrock/anthropic.claude-3-5-sonnet-20240620-v1:0"
o4-mini:
  - "anthropic/claude-3-5-haiku"
  - "gemini/gemini-2.0-flash"
  - "openai/gpt-4.1"
  - "ollama/llama3"
  - "mistral/mistral-small"
  - "bedrock/us.anthropic.claude-3-5-haiku-20241022-v1:0"
codex-mini:
  - "anthropic/claude-3-7-sonnet"
  - "gemini/gemini-2.0-flash"
  - "ollama/gemma3"
  - "mistral/codestral"
  - "bedrock/us.anthropic.claude-3-7-sonnet-20250219-v1:0"
gpt-4o-mini-search:
  - "anthropic/claude-3-5-haiku"
  - "gemini/gemini-1.5-flash"
  - "ollama/llama3"
  - "mistral/mistral-small"
  - "bedrock/us.anthropic.claude-3-7-sonnet-20250219-v1:0"
gpt-4o-search:
  - "anthropic/claude-3-7-sonnet"
  - "gemini/gemini-2.5-pro"
  - "ollama/llama4"
  - "mistral/mistral-large"
  - "bedrock/us.anthropic.claude-3-7-sonnet-20250219-v1:0"

# Anthropic Models
claude-opus-4-0:
  - "openai/o3"
  - "gemini/gemini-2.5-pro"
  - "ollama/deepseek-r1"
  - "mistral/mistral-saba"
  - "bedrock/us.anthropic.claude-opus-4-20250514-v1:0"
claude-sonnet-4-0:
  - "openai/o4-mini"
  - "gemini/gemini-2.0-flash"
  - "ollama/llama4"
  - "mistral/mistral-large"
  - "bedrock/us.deepseek.r1-v1:0"
  - "bedrock/us.anthropic.claude-sonnet-4-20250514-v1:0"
claude-3-7-sonnet:
  - "openai/o4-mini"
  - "gemini/gemini-2.0-flash"
  - "ollama/llama4"
  - "mistral/mistral-large"
  - "bedrock/us.anthropic.claude-3-7-sonnet-20250219-v1:0"
claude-3-5-haiku:
  - "gemini/gemini-2.0-flash"
  - "openai/gpt-4o-mini"
  - "ollama/llama3"
  - "mistral/mistral-small"
  - "bedrock/us.deepseek.r1-v1:0"
  - "bedrock/us.anthropic.claude-3-5-haiku-20241022-v1:0"
claude-3-5-sonnet:
  - "openai/o3-mini"
  - "gemini/gemini-2.0-flash"
  - "ollama/llama4"
  - "mistral/mistral-medium"
  - "bedrock/us.deepseek.r1-v1:0"
  - "bedrock/anthropic.claude-3-5-sonnet-20240620-v1:0"
claude-3-opus:
  - "openai/gpt-4.5"
  - "gemini/gemini-2.5-pro"
  - "ollama/deepseek-r1"
  - "mistral/mistral-saba"
  - "bedrock/us.anthropic.claude-3-opus-20240229-v1:0"

# Gemini Models
gemini-2.5-flash:
  - "openai/gpt-4o-mini"
  - "anthropic/claude-3-5-haiku"
  - "ollama/gemma3"
  - "mistral/mistral-small"
  - "bedrock/us.anthropic.claude-3-5-haiku-20241022-v1:0"
gemini-2.5-pro:
  - "openai/gpt-4.5"
  - "anthropic/claude-sonnet-4-0"
  - "ollama/deepseek-r1"
  - "mistral/mistral-saba"
  - "bedrock/us.anthropic.claude-sonnet-4-20250514-v1:0"
gemini-2.0-flash:
  - "openai/gpt-4o-mini"
  - "anthropic/claude-3-5-haiku"
  - "ollama/llama3"
  - "mistral/mistral-small"
  - "bedrock/us.anthropic.claude-3-5-haiku-20241022-v1:0"
gemini-2.0-flash-lite:
  - "openai/gpt-4o-mini"
  - "anthropic/claude-3-5-haiku"
  - "ollama/llama3"
  - "mistral/mistral-small"
  - "bedrock/amazon.nova-sonic-v1:0"
gemini-1.5-flash:
  - "openai/gpt-4o-mini"
  - "anthropic/claude-3-5-haiku"
  - "ollama/llama3"
  - "mistral/mistral-small"
  - "bedrock/amazon.nova-sonic-v1:0"
gemini-1.5-flash-8b:
  - "openai/gpt-4o-mini"
  - "anthropic/claude-3-5-haiku"
  - "ollama/phi4"
  - "mistral/ministral-8b"
  - "bedrock/amazon.nova-sonic-v1:0"
gemini-1.5-pro:
  - "openai/gpt-4o"
  - "anthropic/claude-3-5-sonnet"
  - "ollama/llama4"
  - "mistral/mistral-medium"
  - "bedrock/anthropic.claude-3-5-sonnet-20240620-v1:0"

# Bedrock models
"claude-3-5-haiku":
  - "gemini/gemini-2.0-flash"
  - "openai/gpt-4o-mini"
  - "anthropic/claude-3-5-haiku"
  - "mistral/mistral-small"
  - "bedrock/us.deepseek.r1-v1:0"
"claude-3-5-sonnet":
  - "openai/o3-mini"
  - "gemini/gemini-2.0-flash"
  - "anthropic/claude-3-5-sonnet"
  - "mistral/mistral-medium"
  - "bedrock/us.deepseek.r1-v1:0"
"claude-3-opus":
  - "openai/gpt-4.5"
  - "gemini/gemini-2.5-pro"
  - "anthropic/claude-3-opus"
  - "anthropic/claude-3-7-sonnet"
  - "mistral/mistral-saba"
  - "bedrock/us.deepseek.r1-v1:0"
"claude-3-7-sonnet":
  - "openai/o4-mini"
  - "gemini/gemini-2.0-flash"
  - "bedrock/us.deepseek.r1-v1:0"
  - "anthropic/claude-3-7-sonnet"
  - "mistral/mistral-large"
"claude-opus-4":
  - "openai/o3"
  - "gemini/gemini-2.5-pro"
  - "bedrock/us.deepseek.r1-v1:0"
  - "anthropic/claude-opus-4-0"
  - "mistral/mistral-saba"
"claude-sonnet-4":
  - "openai/o4-mini"
  - "gemini/gemini-2.0-flash"
  - "bedrock/us.deepseek.r1-v1:0"
  - "anthropic/claude-sonnet-4-0"
  - "mistral/mistral-large"
"r1":
  - "openai/gpt-4o"
  - "anthropic/claude-3-5-sonnet"
  - "gemini/gemini-2.0-flash"
  - "anthropic/claude-3-7-sonnet"
  - "mistral/mistral-large"

# mistral models
ministral-8b:
  - "openai/gpt-4o-mini"
  - "anthropic/claude-3-5-haiku"
  - "gemini/gemini-2.0-flash"
  - "bedrock/us.anthropic.claude-3-5-haiku-20241022-v1:0"
ministral-3b:
  - "openai/gpt-4o-mini"
  - "anthropic/claude-3-5-haiku"
  - "gemini/gemini-1.5-flash-8b"
  - "bedrock/amazon.nova-micro-v1:0"
mistral-small:
  - "openai/gpt-4o-mini"
  - "anthropic/claude-3-5-haiku"
  - "gemini/gemini-2.0-flash"
  - "bedrock/us.anthropic.claude-3-5-haiku-20241022-v1:0"
mistral-medium:
  - "openai/gpt-4o"
  - "anthropic/claude-3-5-sonnet"
  - "gemini/gemini-2.0-flash"
  - "bedrock/anthropic.claude-3-5-sonnet-20240620-v1:0"
mistral-large:
  - "openai/o3"
  - "anthropic/claude-sonnet-4-0"
  - "gemini/gemini-2.5-pro"
  - "bedrock/us.anthropic.claude-3-7-sonnet-20250219-v1:0"
mistral-saba:
  - "openai/o3"
  - "anthropic/claude-opus-4-0"
  - "gemini/gemini-2.5-pro"
  - "bedrock/us.anthropic.claude-opus-4-20250514-v1:0"
magistral-small:
  - "openai/gpt-4o-mini"
  - "anthropic/claude-3-5-haiku"
  - "gemini/gemini-2.0-flash"
  - "bedrock/us.anthropic.claude-3-5-haiku-20241022-v1:0"
magistral-medium:
  - "openai/gpt-4o"
  - "anthropic/claude-3-5-sonnet"
  - "gemini/gemini-2.0-flash"
  - "bedrock/anthropic.claude-3-5-sonnet-20240620-v1:0"
ministral-small:
  - "openai/gpt-4o-mini"
  - "anthropic/claude-3-5-haiku"
  - "gemini/gemini-2.0-flash"
  - "bedrock/us.anthropic.claude-3-5-haiku-20241022-v1:0"
devstral-small:
  - "openai/gpt-4o-mini"
  - "anthropic/claude-3-5-haiku"
  - "gemini/gemini-2.0-flash"
  - "bedrock/us.anthropic.claude-3-5-haiku-20241022-v1:0"
codestral:
  - "openai/gpt-4o"
  - "anthropic/claude-3-5-sonnet"
  - "gemini/gemini-2.0-flash"
  - "bedrock/anthropic.claude-3-5-sonnet-20240620-v1:0"
open-mistral-nemo:
  - "openai/gpt-4o"
  - "anthropic/claude-3-5-sonnet"
  - "gemini/gemini-2.0-flash"
  - "bedrock/anthropic.claude-3-5-sonnet-20240620-v1:0"
mistral-ocr:
  - "openai/gpt-4o-mini"
  - "anthropic/claude-3-5-haiku"
  - "gemini/gemini-2.0-flash"
  - "bedrock/us.anthropic.claude-3-5-haiku-20241022-v1:0"


# Ollama Models
deepseek-r1:
  - "openai/gpt-4o"
  - "anthropic/claude-3-5-sonnet"
  - "gemini/gemini-2.0-flash"
  - "mistral/mistral-large"
  - "bedrock/us.deepseek.r1-v1:0"
llama4:
  - "openai/gpt-4o"
  - "anthropic/claude-3-5-sonnet"
  - "gemini/gemini-2.0-flash"
  - "mistral/mistral-large"
  # bedrock doesn't have fullsize llama4
  - "bedrock/us.deepseek.r1-v1:0"
llama3.3:
  - "openai/gpt-4o-mini"
  - "anthropic/claude-3-5-haiku"
  - "gemini/gemini-1.5-flash"
  - "mistral/mistral-small"
  - "bedrock/meta.llama3-8b-instruct-v1:0"
llama3:
  - "openai/gpt-4o-mini"
  - "anthropic/claude-3-5-haiku"
  - "gemini/gemini-1.5-flash"
  - "mistral/mistral-small"
  - "bedrock/meta.llama3-8b-instruct-v1:0"
gemma3:
  - "openai/gpt-4o-mini"
  - "anthropic/claude-3-5-haiku"
  - "gemini/gemini-1.5-flash"
  - "mistral/mistral-small"
  - "bedrock/us.deepseek.r1-v1:0"
qwen3:
  - "openai/gpt-4o-mini"
  - "anthropic/claude-3-5-haiku"
  - "gemini/gemini-1.5-flash"
  - "mistral/mistral-small"
  - "bedrock/us.deepseek.r1-v1:0"
phi4:
  - "openai/gpt-4o-mini"
  - "anthropic/claude-3-5-haiku"
  - "gemini/gemini-1.5-flash"
  - "mistral/ministral-3b"
  - "bedrock/amazon.nova-lite-v1:0"
llava:
  - "openai/gpt-4o-mini"
  - "anthropic/claude-3-5-haiku"
  - "gemini/gemini-1.5-flash"
  - "mistral/mistral-small"
  - "bedrock/us.deepseek.r1-v1:0"
