openai:
  models:
    - "gpt-4"
    - "gpt-4-turbo"
    - "gpt-4o"
    - "gpt-4o-mini"
    - "gpt-4.1"
    - "gpt-4.1-mini"
    - "gpt-4.1-nano"
    - "gpt-4.5"
    - "o1"
    - "o1-mini"
    - "o1-pro"
    - "o3"
    - "o3-mini"
    - "o4-mini"
    - "codex-mini"
    - "gpt-4o-mini-search"
    - "gpt-4o-search"
  base-url: https://api.openai.com

anthropic:
  models:
    - "claude-opus-4-0"
    - "claude-sonnet-4-0"
    # the alias Anthropic provides for these below models require that it
    # include an explicit `-latest` suffix when sent to Antrhopic
    - "claude-3-7-sonnet"
    - "claude-3-5-haiku"
    - "claude-3-5-sonnet"
    - "claude-3-opus"
  base-url: https://api.anthropic.com
  version: "2023-06-01"

gemini:
  models:
    - "gemini-2.5-flash"
    - "gemini-2.5-pro"
    - "gemini-2.0-flash"
    - "gemini-2.0-flash-lite"
    - "gemini-1.5-flash"
    - "gemini-1.5-flash-8b"
    - "gemini-1.5-pro"
  base-url: https://generativelanguage.googleapis.com

mistral:
  models:
    - "ministral-8b"
    - "ministral-3b"
    - "mistral-small"
    - "mistral-medium"
    - "mistral-large"
    - "mistral-saba"
    - "magistral-small"
    - "magistral-medium"
    - "ministral-small"
    - "devstral-small"
    - "codestral"
    - "open-mistral-nemo"
    - "mistral-ocr"
  base-url: https://api.mistral.ai

ollama:
  models:
    - "deepseek-r1"
    - "gemma3"
    - "qwen3"
    - "llama4"
    - "llama3.3"
    - "llama3.2"
    - "llama3"
    - "phi4"
    - "llava"
  base-url: http://localhost:11434

bedrock:
  # bedrock models must be enabled prior to sending
  # requests which use them
  models:
    - "claude-3-5-haiku"
    - "claude-3-5-sonnet"
    - "claude-3-opus"
    - "claude-3-7-sonnet"
    - "claude-opus-4"
    - "claude-sonnet-4"
    - "r1"
    - "nova-premier"
    - "titan-text-premier"
    - "titan-text-express"
    - "titan-text-lite"
    - "nova-sonic"
    - "nova-pro"
    - "nova-lite"
    - "nova-micro"
    - "jamba-1-5-large"
    - "jamba-1-5-mini"
    - "command-light-text"
    - "command-r-plus"
    - "command-text"
    - "llama3-8b-instruct"
    - "llama3-70b-instruct"
    - "llama3-1-8b-instruct"
    - "llama3-2-1b-instruct"
    - "llama3-2-3b-instruct"
    - "llama3-2-90b-instruct"
    - "llama4-maverick-17b-instruct"
    - "mistral-7b-instruct"
    - "mistral-large-2402"
    - "mistral-small-2402"
    - "mixtral-8x7b-instruct"
    - "pixtral-large-2502"
  base-url: https://bedrock-runtime.us-east-1.amazonaws.com
