[workspace]
members = [
  "crates/anthropic-types",
  "crates/openai-types",
  "crates/schema-filter",
  "worker",
  "worker-test",
]
resolver = "2"

[workspace.package]
edition = "2024"
authors = ["Thomas Harmon <thomas.alan.harmon@gmail.com>"]
license = "MIT"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = true


[workspace.dependencies]
openai-types = { path = "./crates/openai-types" }
anthropic-types = { path = "./crates/anthropic-types" }
llm-proxy = { path = "./worker" }

worker = { version="0.5.0", features=['http'] }
worker-macros = { version="0.5.0", features=['http'] }
console_error_panic_hook = { version = "0.1.1" }
http = "1.1"

url = "2.5.4"
hyper = { version = "1.6.0", features = ['full'] }
tower-http = "0.6.2"
futures = "0.3.31"
bytes = "1.10.1"
serde = { version = "1.0.219", features = ["derive", "rc"] }
serde_with = "3.12.0"
derive_more = { version = "2.0.1", features = ['as_ref', 'constructor', 'debug', 'deref', 'display', 'from', 'from_str'] }
indexmap = "2.8.0"
isocountry = "0.3.2"
tokio = { version = "1.44.1", features = ['full'] }
serde_json = "1.0.140"
derive_builder = "0.20.2"
thiserror = "2.0.11"
reqwest = { version = "0.12.12", features = [
  "json",
  "stream",
  "multipart",
], default-features = false }
tracing = "0.1.41"
base64 = "0.22.1"
# Schema filter dependencies
clap = { version = "4.5.34", features = ["derive"] }
serde_yaml = "0.9.33"
openapiv3 = "2.0"
anyhow = "1.0.97"
serde_repr = "0.1.20"
tower = "0.5.2"
http-body-util = "0.1.3"
rust_decimal = "1.37.1"
pin-project-lite = "0.2.16"