[workspace]
members = [
  "crates/anthropic-types",
  "crates/openai-types",
  "crates/schema-filter",
  "llm-proxy",
  "worker-test",
]
resolver = "2"

[workspace.package]
edition = "2024"
authors = ["Thomas Harmon <thomas.alan.harmon@gmail.com>"]
license = "MIT"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = true


[workspace.dependencies]
openai-types = { path = "./crates/openai-types" }
anthropic-types = { path = "./crates/anthropic-types" }
llm-proxy = { path = "./llm-proxy" }

anyhow = "1.0.97"
base64 = "0.22.1"
bytes = "1.10.1"
clap = { version = "4.5.34", features = ["derive"] }
derive_builder = "0.20.2"
derive_more = { version = "2.0.1", features = ['as_ref', 'constructor', 'debug', 'deref', 'display', 'from', 'from_str'] }
futures = "0.3.31"
http = "1.1"
http-body-util = "0.1.3"
hyper = { version = "1.6.0", features = ['full'] }
hyper-util = "0.1.11"
indexmap = "2.8.0"
isocountry = "0.3.2"
openapiv3 = "2.0"
pin-project-lite = "0.2.16"
reqwest = { version = "0.12.12", features = [ "json", "stream", "multipart", "native-tls"], default-features = false }
rust_decimal = "1.37.1"
serde = { version = "1.0.219", features = ["derive", "rc"] }
serde_json = "1.0.140"
serde_repr = "0.1.20"
serde_with = "3.12.0"
serde_yaml = "0.9.33"
thiserror = "2.0.11"
tokio = { version = "1.44.2", features = ['full'] }
tower = "0.5.2"
tower-http = "0.6.2"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
url = "2.5.4"