app = "helicone-ai-gateway"
primary_region = "iad"

[build]
  image = "helicone/ai-gateway:main"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "off"
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory = "512mb"

[[http_service.checks]]
  grace_period = "5s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/health"

[experimental]
cmd = ["/usr/local/bin/ai-gateway", "-c", "/app/config/config.yaml"]

[[files]]
  guest_path = "/app/config/config.yaml"
  raw_value = '''

routers:
  default:
    load-balance:
      chat:
        strategy: latency
        providers:
          - openai
          - anthropic

helicone-observability:
  enable-auth: true
'''

# [[files]]
#   guest_path = "/app/config/config.yaml"
#   local_path = "ai-gateway/config/sidecar.yaml"