global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090
  - job_name: tempo
    static_configs:
      - targets:
          - rockstar-tempo.internal:3200
  - job_name: loki
    static_configs:
      - targets:
          - rockstar-loki.internal:3100
  - job_name: minio
    metrics_path: /minio/v2/metrics/cluster
    scheme: https
    static_configs:
      - targets:
          - rockstar-minio.internal:5532
  - job_name: rockstar-api
    static_configs:
      - targets:
          - rockstar-api.internal:5679
