# OpenAI Models
gpt-4:
  - claude-3-7-sonnet
  - gemini-2.5-pro
  - deepseek-r1
gpt-4-turbo:
  - claude-3-7-sonnet
  - gemini-2.5-pro
  - llama4
gpt-4o:
  - claude-3-7-sonnet
  - gemini-2.5-pro
  - llama4
gpt-4o-mini:
  - claude-3-5-haiku
  - gemini-2.0-flash
  - llama3.2
  - llama3
gpt-4.1:
  - claude-3-7-sonnet
  - gemini-2.5-pro
  - llama4
gpt-4.1-mini:
  - claude-3-5-haiku
  - gemini-2.0-flash
  - llama3.3
gpt-4.1-nano:
  - claude-3-5-haiku
  - gemini-1.5-flash-8b
  - phi4
gpt-4.5:
  - claude-opus-4-0
  - gemini-2.5-pro
  - deepseek-r1
o1:
  - claude-4-0-sonnet
  - gemini-2.5-pro
  - deepseek-r1
o1-mini:
  - claude-3-5-haiku
  - gemini-2.0-flash
  - llama3.3
o1-pro:
  - claude-opus-4-0
  - gemini-2.5-pro
  - deepseek-r1
o3:
  - claude-opus-4-0
  - gemini-2.5-pro
  - deepseek-r1
o3-mini:
  - claude-3-5-haiku
  - gemini-2.0-flash
  - llama3.3
o4-mini:
  - gemini-2.0-flash
  - gpt-4.1
  - llama3
codex-mini:
  - claude-3-7-sonnet
  - gemini-2.0-flash
  - gemma3
gpt-4o-mini-search:
  - claude-3-5-haiku
  - gemini-1.5-flash
  - llama3
gpt-4o-search:
  - claude-3-7-sonnet
  - gemini-2.5-pro
  - llama4

# Anthropic Models
claude-opus-4-0:
  - o3
  - gemini-2.5-pro
  - deepseek-r1
claude-sonnet-4-0:
  - o4-mini
  - gemini-2.0-flash
  - llama4
claude-3-7-sonnet:
  - o4-mini
  - gemini-2.0-flash
  - llama4
claude-3-5-haiku:
  - gemini-2.0-flash
  - gpt-4o-mini
  - llama3
claude-3-5-sonnet:
  - o3-mini
  - gemini-2.0-flash
  - llama4
claude-3-opus:
  - gpt-4.5
  - gemini-2.5-pro
  - deepseek-r1

# Gemini Models
gemini-2.5-flash:
  - gpt-4o-mini
  - claude-3-5-haiku
  - gemma3
gemini-2.5-pro:
  - gpt-4.5
  - claude-opus-4-0
  - deepseek-r1
gemini-2.0-flash:
  - gpt-4o-mini
  - claude-3-5-haiku
  - llama3
gemini-2.0-flash-lite:
  - gpt-4o-mini
  - claude-3-5-haiku
  - llama3
gemini-1.5-flash:
  - gpt-4o-mini
  - claude-3-5-haiku
  - llama3
gemini-1.5-flash-8b:
  - gpt-4o-mini
  - claude-3-5-haiku
  - phi4
gemini-1.5-pro:
  - gpt-4o
  - claude-3-5-sonnet
  - llama4

# Ollama Models
deepseek-r1:
  - gpt-4o
  - claude-3-5-sonnet
  - gemini-2.0-flash
llama4:
  - gpt-4o
  - claude-3-5-sonnet
  - gemini-2.0-flash
llama3.3:
  - gpt-4o-mini
  - claude-3-5-haiku
  - gemini-1.5-flash
llama3:
  - gpt-4o-mini
  - claude-3-5-haiku
  - gemini-1.5-flash
gemma3:
  - gpt-4o-mini
  - claude-3-5-haiku
  - gemini-1.5-flash
qwen3:
  - gpt-4o-mini
  - claude-3-5-haiku
  - gemini-1.5-flash
phi4:
  - gpt-4o-mini
  - claude-3-5-haiku
  - gemini-1.5-flash
llava:
  - gpt-4o-mini
  - claude-3-5-haiku
  - gemini-1.5-flash
