version: '3.8'

services:
  # Build Linux glibc binary
  build-linux:
    build:
      context: ../..
      dockerfile: npx/docker/Dockerfile.linux
    volumes:
      - ../dist:/dist
    command: cp /output/helicone-router-linux /dist/
    
  # Build Linux musl binary (Alpine-compatible)
  build-linux-musl:
    build:
      context: ../..
      dockerfile: npx/docker/Dockerfile.linux-musl
    volumes:
      - ../dist:/dist
    command: cp /output/helicone-router-linux-musl /dist/

  # Test Ubuntu compatibility
  test-ubuntu:
    image: ubuntu:20.04
    depends_on:
      - build-linux
    volumes:
      - ../dist:/test:ro
    command: >
      bash -c "
        chmod +x /test/helicone-router-linux &&
        echo 'Testing Ubuntu compatibility:' &&
        /test/helicone-router-linux --help &&
        echo '✅ Ubuntu compatibility confirmed'
      "

  # Test Alpine compatibility  
  test-alpine:
    image: alpine:latest
    depends_on:
      - build-linux-musl
    volumes:
      - ../dist:/test:ro
    command: >
      sh -c "
        chmod +x /test/helicone-router-linux-musl &&
        echo 'Testing Alpine compatibility:' &&
        /test/helicone-router-linux-musl --help &&
        echo '✅ Alpine compatibility confirmed'
      " 