providers:
  openai:
    base-url: "http://localhost:8100"
  anthropic:
    base-url: "http://localhost:8101"
  gemini:
    base-url: "http://localhost:8102"

minio:
  host: "http://localhost:8103"

helicone:
  base-url: "http://localhost:8104"
  websocket-url: "ws://localhost:8585/ws/v1/router/control-plane"
  authentication: true
  observability: true

telemetry:
  level: info,ai_gateway=debug
  exporter: both