telemetry:
  level: "info,ai_gateway=trace"
  exporter: both

helicone:
  base-url: "http://localhost:8585"
  websocket-url: "ws://localhost:8585/ws/v1/router/control-plane"
  features: none

global:
  cache:
    directive: "max-age=10"

cache-store:
  type: in-memory

routers:
  my-router:
    load-balance:
      chat:
        strategy: model-latency
        models:
          - bedrock/anthropic.claude-3-7-sonnet-v1:0
          - anthropic/claude-3-7-sonnet