telemetry:
  level: "info,ai_gateway=trace"
  exporter: both

helicone-observability:
  base-url: "http://localhost:8585"
  websocket-url: "ws://localhost:8585/ws/v1/router/control-plane"
  enable-auth: true

routers:
  default:
    load-balance:
      chat:
        strategy: latency
        providers:
          - gemini