telemetry:
  level: "info,ai_gateway=trace"
  exporter: both

helicone:
  base-url: "http://localhost:8585"
  websocket-url: "ws://localhost:8585/ws/v1/router/control-plane"
  features: all

deployment-target: sidecar

# cache-store:
#   type: redis
#   host-url: "redis://localhost:6379"

routers:
  my-router:
    load-balance:
      chat:
        strategy: latency
        providers:
          - openai
          - gemini