server:
  address: 0.0.0.0
  port: 8080

routers:
  default:
    load-balance:
      chat:
        strategy: latency
        providers:
          - openai
          - anthropic

helicone-observability:
  enable-auth: true