name: Rust CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  format:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Use nightly rustfmt
        run: rustup component add --toolchain nightly-x86_64-unknown-linux-gnu rustfmt
      - name: Output rustup and cargo version for educational purposes
        run: rustup --version && echo "\n" && cargo --version
      - name: Format
        run: cargo +nightly fmt --check
  clippy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: print version
        run: cargo --version
      - name: Clippy
        run: cargo +stable ci-clippy
  test:
    runs-on: self-hosted
    env:
      HELICONE_API_KEY: "sk-helicone-..."
    services:
      redis:
        image: redis:6.2.6-alpine
        ports:
          - 6379:6379

    steps:
      - uses: actions/checkout@v4
      - name: Test
        run: cargo +stable test --tests --all-features
